### ISSUE TITLE
Add JSF 2.2 support 

### ISSUE THREAD

**Issue by gilbertoca** [marschall/threeten-jpa#10]
Hi, thank you for the API.
I'm using it with PostgreSQL and JPA 2.1 (eclipselink). Is it possible to add support for JSF converter?
Unfortunately we can't use one converter for both API, so code duplication is inevitable. But unifying it in the same API improves maintainability.

Regards

**Comment by marschall** [comment]
I'm not familiar with JSF converters. Is this a good start?
http://docs.oracle.com/javaee/6/tutorial/doc/bnaus.html
do you have other pointers for me, especially when it comes to automated testing?

**Comment by gilbertoca** [comment]
Have used this discussion http://stackoverflow.com/questions/34883270/how-to-use-java-time-zoneddatetime-localdatetime-in-pcalendar to create my one

**Comment by marschall** [comment]
Thank you, I'll have a look.

**Comment by marschall** [comment]
I am a bit reluctant about doing this for several reasons:

1. I am not familiar with JSF, for example I don't know how to write automated integration tests for JSF converters
1. This project is about JPA, JSF support would IMO have to go to a different project or the project would have to be renamed.
1. It is already fixed in JSF 2.3 milestones ([Utilizing the JSF 2.3 f:convertDateTime Tag with the Java 8 Date-Time API](http://jj-blogger.blogspot.ch/2015/12/utilizing-jsf-23-fconvertdatetime-tag.html), [What's new in JSF 2.3?](http://arjan-tijms.omnifaces.org/p/jsf-23.html)), additional work have to be spent to aligning it with JSF 2.3 API.
1. I am not a big fan of hard coding time zones or patterns in the source code, IMHO this should come from user settings which would be intrusive to the application.

**Comment by gilbertoca** [comment]
@marschall  
> I am not familiar with JSF, for example I don't know how to write automated integration tests for JSF converters
I think no one knows, unfortunately.
 
> This project is about JPA, JSF support would IMO have to go to a different project or the project would have to be renamed.
I agree.

> It is already fixed in JSF 2.3 milestones (Utilizing the JSF 2.3 f:convertDateTime Tag with the Java 8 Date-Time API, What's new in JSF 2.3?), additional work have to be spent to aligning it with JSF 2.3 API.
No one will be using it any time soon. Java EE 8 is target to 2017. We need it now.

> I am not a big fan of hard coding time zones or patterns in the source code, IMHO this should come from user settings which would be intrusive to the application.
I agree. I was hoping a converter in the JPA style - the simplest one.

Thank you very much for looking into this.

**Comment by marschall** [comment]
Are you currently using ISO strings?
If so I could make a simple project that just does ISO String ↔ LocalDate(Time) conversion without any intention of doing anything more sophisticated.

**Comment by gilbertoca** [comment]
@marschall I've been using [my own converter] (https://gist.github.com/gilbertoca/863a0027e6c0d497b8825695599a9dc0) . It is based on the discussion's stackoverflow.com. I comprehend you reasons. You can close this issue.
Thank you.
