### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by Ramblurr** [marschall/threeten-jpa#22]
The support matrix in the readme conveys that timezone support works with hibernate and postgres when using the `threeten-jpa-jdbc42-hibernate` module.

However, the supplementary text about JDBC 4.2 drivers is a little unclear.

Does timezone support work as expected with the postgres driver >= 9.5? Or is there data loss that occurs when saving `ZonedDateTime` types (and postgres presumably strips the TZ data)?

**Comment by marschall** [comment]
Yes Postgres is supported using the `threeten-jpa-jdbc42-hibernate` module when you use the 9.4.1208 driver or later.

The following caveats apply:

 * `ZonedDateTime` is not supported, it is also not mentioned in the [JDBC 4.2 specification](http://download.oracle.com/otndocs/jcp/jdbc-4_2-mrel2-spec/index.html).
 * `OffsetDateTime` is supported with the `TIMESTAMP WITH TIME ZONE` type, however all data is stored in UTC. Eg. when you store `2017-01-16T13:30:02.367+01:00` what is actually stored (and returned) is `2017-01-16T12:30:02.367Z`. This is a [limitation](https://www.postgresql.org/docs/current/static/datatype-datetime.html#AEN6182) of Postgres.
 * `LocalTime` is limited seconds resolution, see [PR 691](https://github.com/pgjdbc/pgjdbc/pull/691)

**Comment by Ramblurr** [comment]
Hm, so in the case of postgres does this library buy you anything when using hibernate 5.2?

**Comment by marschall** [comment]
Yes, storing the zone it in a different field is probably the best option. This should be doable with a Hibernate converter.

Yes, even with Postgres and Hibernate 5.2 this library offers advantages:
1. When using `LocalDateTime / TIMESTAMP` you avoid issues around DST transitions with ambiguous or not existing times.
1. Even with `OffsetDateTime / TIMESTAMP WITH TIME ZONE` in UTC the correct instant is always preserved. This is hard to do with `LocalDateTime / TIMESTAMP` alone because because it relies on the same time zone settings for all clients and script executions.

**Comment by Ramblurr** [comment]
Thanks for the quick responses. The Hibernate 5 section could be clarified slightly, as I parsed that paragraph as stating the library was only beneficial over the hibernate 5.0+hibernate-java8 and not necessary with hibernate 5.2.

Do you have any plans to provide a custom converter that stores `ZonedDateTime` in two fields?

**Comment by marschall** [comment]
I agree, the documentation can be clarified. I'll keep this issue open for this.

I have no immediate plans for supporting `ZonedDateTime` with two fields. Feel free to file an issue for this but I can't give out a estimated completion date. I would be willing to accept a pull request.

**Comment by marschall** [comment]
I updated to documentation to hopefully be a bit clearer, added a wiki page for [JDBC-4.2](https://github.com/marschall/threeten-jpa/wiki/JDBC-4.2) and opened #25.

**Comment by marschall** [comment]
@Ramblurr I have an experimental composite user type as part of #25. It stores the timestamp as UTC in one column and the time zone id in a second. However due to limitations in Hibernate it is quite limited at the time.

* only works with Hibernate, duh
* equality comparisons (=) always consider the name of the time zone
* other comparisons (&lt;, &lt;=, &gt;=, &gt;) are not supported with JPQL or criteria API, see [HHH-7302](https://hibernate.atlassian.net/browse/HHH-7302)

These make it quite likely that you have to drop to a native SQL query if you're doing any kind of filtering on these columns. Unfortunately binding `OffsetDateTime` is hit and miss with Hibernate, see [HHH-11773](https://hibernate.atlassian.net/browse/HHH-11773).
So I'm not quite sure how helpful this will be.

**Comment by Ramblurr** [comment]
Very interesting @marschall. Your effort is much appreciated.

Those are some unfortunate limitations indeed. Are there any possible workarounds or future fixes to Hibernate that will make full support possible? Or will this be the cutting edge for some time to come?

**Comment by marschall** [comment]
@Ramblurr it looks like I spoke too soon. In JPQL you can access the individual components of the composite type

```sql
SELECT t
FROM MyEntity t
WHERE t.zonedDateTimeColumn.timestamp_utc < :value
```

```sql
SELECT t
FROM MyEntity t
WHERE t.zonedDateTimeColumn.zoneid = :zoneid
```

It it should very well be possible to avoid native SQL and use JPQL for those scenarios. Just not with criteria API.
