### ISSUE TITLE
Support for org.threeten.extra.Interval

### ISSUE THREAD

**Issue by mujehoxe** [marschall/threeten-jpa#60]
Note. the interval type is different from period and duration in that interval keeps hold of the beginning and end of an interval, and provides operations such that is an instant in time contained in interval, or does to intervals overlap.

**Comment by marschall** [comment]
What would this map to? Postgres [tstzrange](https://www.postgresql.org/docs/current/rangetypes.html)? If so Postgres range types seem more flexible than `org.threeten.extra.Interval` when it comes to their bounds, any combination of inclusive, exclusive and unbounded is possible.

See also https://github.com/pgjdbc/pgjdbc/pull/947

**Comment by mujehoxe** [comment]
Seems as if hibernate support these ranges
[How to map a PostgreSQL Range column type with JPA and Hibernate](https://vladmihalcea.com/map-postgresql-range-column-type-jpa-hibernate/)

**Comment by marschall** [comment]
Right, Hibernate Types maps Postgres ranges to a custom range type matching Postgres semantics. I currently don't see how we could improve on this. If Hibernate Types does what you need then my recommendation would be to use Hibernate Types.

**Comment by mujehoxe** [comment]
Isn't about improving upon it but to make you library more complete to its goal, which i think is mapping between java 8 date and time, and interval is a part of that. and i also think that your library would be much lighter than hibernate types.

**Comment by marschall** [comment]
Sure but:
* `org.threeten.extra.Interval` is not JSR-310 but an extra class.
* The only database I'm aware of that supports date ranges types is Postgres.
* Postgres date range types have different semantics than `org.threeten.extra.Interval`, which means we can't map them to `org.threeten.extra.Interval`.
* Which means there is no JSR-310 or extra type that we can map Postgres date ranges to.
* Which means we need to create a specific type for Postgres that has no relationship to any JSR-310 or extra type.
* In addition since accessing Postgres range types requires access to driver extensions we will need access to the JDBC `ResultSet` and `PreparedStatement` which means it can't be done through a JPA `AtributeConverter` but only through a Hibernate `UserType`.

In the end we end up with the exact same code as Hibernate Types that has no relationship to JSR-310 or extra. In addition Hibernate Types supports several Hibernate versions.
